# This workflow only lints the code and runs unit tests.
# It intentionally does not execute any report generation code - this keeps it lightweight, indicating basic levels
# of health for this repository (for pull requests and the `main` branch).

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint and Test
        run: |
          npm ci
          npm run lint
          npm run test
