# This workflow only executes for pull requests.
# It is designed to give us a check indicating whether the report generation runs and generates some output.
# The idea is that if a given pull request passes this check then we expect it to succeed with the run.yml workflow.

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Report
        env:
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID_ABLY: ${{ secrets.APP_INSTALLATION_ID_ABLY }}
        run: |
          npm ci
          echo "$APP_PRIVATE_KEY" > app-private-key.pem
          node .
          rm app-private-key.pem

      - name: Validate Report Output Not Empty
        run: |
          grep 'Repository Audit' output/report/ably.md
          grep 'Generated by:' output/commit-message.txt
