# This workflow only executes for pull requests.
# It has been designed specifically to only work when triggered with the `pull_request` workflow event.

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Generate Report
        env:
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID_ABLY: ${{ secrets.APP_INSTALLATION_ID_ABLY }}
        run: |
          npm ci
          echo "$APP_PRIVATE_KEY" > app-private-key.pem
          node .
          rm app-private-key.pem

      - name: Publish Report Preview
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ABLY_REPOSITORY_AUDIT_REPORT_SSH_KEY }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh-private-key.pem
          chmod 400 ssh-private-key.pem
          eval $(ssh-agent -s)
          scripts/configure-ssh-and-git.sh
          scripts/publish.sh "${PULL_REQUEST_NUMBER}"
