# This is a manually triggered workflow (hence on: workflow_dispatch).
# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events

on:
  # allow us to run this workflow manually when required - for example to update the report after changes have been
  # made to repository configurations
  workflow_dispatch:

  # always run this workflow when we push commits to the default branch
  push:
    branches:
      - main

  # run against the latest commit on the default branch daily at just before 6am
  schedule:
    - cron: '55 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Audit and Generate Report
        env:
          APP_CLIENT_SECRET: ${{ secrets.APP_CLIENT_SECRET }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_CLIENT_ID: ${{ secrets.APP_CLIENT_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID_ABLY: ${{ secrets.APP_INSTALLATION_ID_ABLY }}
        run: |
          npm ci
          echo "$APP_PRIVATE_KEY" > app-private-key.pem
          node .

      - name: Publish Internal Report
        env:
          SSH_PRIVATE_KEY: ${{ secrets.INTERNAL_REPORT_REPOSITORY_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh-private-key.pem
          chmod 400 ssh-private-key.pem
          eval $(ssh-agent -s)
          scripts/configure-ssh-and-git.sh
          scripts/publish.sh internal ably/repository-audit-report-internal

      - name: Publish Public Report
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PUBLIC_REPORT_REPOSITORY_SSH_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh-private-key.pem
          chmod 400 ssh-private-key.pem
          eval $(ssh-agent -s)
          scripts/configure-ssh-and-git.sh
          scripts/publish.sh public ably/repository-audit-report
